# Server config
server.port=8080

# Datasource config
spring.datasource.url=jdbc:mysql://localhost:3306/vamshi
spring.datasource.username=root
spring.datasource.password=vaanara
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Mail config (local SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=krishnasait0951@gmail.com
spring.mail.password=kzap cwhq azmt ywcj
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# JWT config
jwt.secret=849dc646881d1f09f1efba30100badb63f12ac4b899694a4f0dd01dd7998638d
jwt.expiration.ms=86400000

springdoc.swagger-ui.path=/swagger-ui.html


# Logging config
logging.level.com.example.userservice=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
