server:
  port: 9090

spring:
  application:
    name: admin-server
    
  security:
    user:
      name: admin
      password: admin


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
