server:
  port: 9090

spring:
  application:
    name: admin-server

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env

security:
  user:
    name: admin
    password: admin
